-- issued_invoices: invoices and credit notes generated by the ERP/billing system
CREATE TABLE public.issued_invoices (
    doc_number          VARCHAR(100) PRIMARY KEY,   -- invoice/credit note document number
    customer_id         CHAR(8) NOT NULL REFERENCES public.customers(customer_id) ON DELETE CASCADE,
    contract_number     VARCHAR(100) REFERENCES public.contracts(contract_number),
    document_type       VARCHAR(20) NOT NULL,      -- 'INVOICE' or 'CREDIT_NOTE'
    issue_date          DATE NOT NULL,             -- document issue date
    due_date            DATE NOT NULL,             -- due date 
    amount              NUMERIC(12,2) NOT NULL,    -- value in original currency
    currency            VARCHAR(10) NOT NULL,      -- original currency
    description         TEXT,                       -- optional: ERP description
    type                TEXT NOT NULL DEFAULT 'LEASE'::TEXT,
    doc_reference       VARCHAR(100),
    created_at          TIMESTAMPTZ DEFAULT NOW()
);